unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

set -g default-terminal "screen-256color"

# Change bind key
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

# Enable mouse mode
set -g mouse on

# Use vim keybindings
setw -g mode-keys vi

# Easy split commands
unbind '"'
unbind %
bind - split-window -v
bind = split-window -h 

# Navigate using Alt without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D 

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

## Vimlike navigation
set -g @plugin 'christoomey/vim-tmux-navigator'

## Theme
set -g @plugin "arcticicestudio/nord-tmux"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
