unbind r
bind r source-file ~/.tmux.conf \; display-message "Config reloaded..."

# Change bind key
set -g prefix C-a

# Enable mouse mode
set -g mouse on

# Use vim keybindings
setw -g mode-keys vi

# Easy split commands
unbind '"'
unbind %
bind - split-window -v
bind = split-window -h 

# Navigate using Alt without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D 

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# List of plugins
#set -g @plugin 'tmux-plugins/tpm'
#set -g @plugin 'dracula/tmux'

#:et -g @dracula-show-powerline true
#set -g @dracula-fixed-location "NYC"
#set -g @dracula-plugins "weather"
#set -g @dracula-show-flags true
#set -g @dracula-show-left-icon session
#set -g status-position top

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# run '~ tmux/plugins/tpm/tpm:
